spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/perfume_shop?createDatabaseIfNotExist=true&serverTimezone=Europe/Copenhagen}
spring.datasource.username=${DB_USERNAME:perfume}
spring.datasource.password=${DB_PASSWORD:perfume}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false
