package aljamour.perfumeshop.config;

import aljamour.perfumeshop.model.Gender;

import java.util.List;

final class CatalogSeedData {

    private CatalogSeedData() {}

    static List<ProductSeed> products() {
        return List.of(
            new ProductSeed("001", "One Million", "Paco Rabanne", Gender.MEN, "one-million", true, List.of(15, 30, 70), List.of("popular", "date-night")),
            new ProductSeed("002", "Acqua Di Gio", "Giorgio Armani", Gender.MEN, "acqua-di-gio", true, List.of(15, 30, 70), List.of("popular", "summer")),
            new ProductSeed("003", "Fahrenheit", "Christian Dior", Gender.MEN, "fahrenheit", false, List.of(15, 35, 70), List.of()),
            new ProductSeed("004", "The One", "Dolce & Gabbana", Gender.MEN, "the-one-men", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("150M", "Hugo", "Hugo Boss", Gender.MEN, "hugo-men", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("006", "Opium", "Yves Saint Laurent", Gender.WOMEN, "opium", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("007", "J’Adore", "Christian Dior", Gender.WOMEN, "jadore", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("010", "Alien", "Thierry Mugler", Gender.WOMEN, "alien", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("011", "Light Blue", "Dolce & Gabbana", Gender.WOMEN, "light-blue-women", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("012", "Eau Sauvage", "Christian Dior", Gender.MEN, "eau-sauvage", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("151W", "Guilty", "Gucci", Gender.WOMEN, "guilty-women", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("014", "Manifesto", "Yves Saint Laurent", Gender.WOMEN, "manifesto", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("015", "Roma", "Laura Biagiotti", Gender.WOMEN, "roma", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("016", "Le Mâle", "Jean Paul Gaultier", Gender.MEN, "le-male", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("152M", "Guilty", "Gucci", Gender.MEN, "guilty-men", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("018", "Déclaration", "Cartier", Gender.MEN, "declaration", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("019", "Lady Million", "Paco Rabanne", Gender.WOMEN, "lady-million", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("020", "La Nuit de l’Homme", "Yves Saint Laurent", Gender.MEN, "la-nuit-de-lhomme", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("021", "Light Blue", "Dolce & Gabbana", Gender.MEN, "light-blue-men", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("022", "Terre d’Hermès", "Hermès", Gender.MEN, "terre-dhermes", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("023", "Hypnotic Poison", "Christian Dior", Gender.WOMEN, "hypnotic-poison", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("024", "Chanel N°5", "Chanel", Gender.WOMEN, "chanel-n5", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("025", "For Her", "Narciso Rodriguez", Gender.WOMEN, "for-her", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("026", "Flower", "Kenzo", Gender.WOMEN, "flower", false, List.of(15, 35, 70), List.of()),
            new ProductSeed("027", "Trésor", "Lancôme", Gender.WOMEN, "tresor", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("028", "Angel", "Thierry Mugler", Gender.WOMEN, "angel", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("029", "Eau D’Issey", "Issey Miyake", Gender.WOMEN, "eau-dissey", false, List.of(15, 30, 100), List.of()),
            new ProductSeed("030", "Black XS", "Paco Rabanne", Gender.MEN, "black-xs", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("032", "Spicebomb", "Viktor & Rolf", Gender.MEN, "spicebomb", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("033", "Black Code", "Giorgio Armani", Gender.MEN, "black-code", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("037", "Man", "Bvlgari", Gender.MEN, "bvlgari-man", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("038", "Bleu", "Chanel", Gender.MEN, "bleu-de-chanel", true, List.of(15, 30, 70), List.of("popular", "office")),
            new ProductSeed("039", "Miss Dior Chérie", "Christian Dior", Gender.WOMEN, "miss-dior-cherie", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("040", "Hypnôse", "Lancôme", Gender.WOMEN, "hypnose", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("153W", "Chloé", "Chloé", Gender.WOMEN, "chloe", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("042", "La Vie Est Belle", "Lancôme", Gender.WOMEN, "la-vie-est-belle", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("154W", "Love, Chloé", "Chloé", Gender.WOMEN, "love-chloe", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("044", "Silver Mountain Water", "Creed", Gender.UNISEX, "silver-mountain-water", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("155U", "CK One", "Calvin Klein", Gender.UNISEX, "ck-one", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("047", "Crystal Noir", "Versace", Gender.WOMEN, "crystal-noir", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("048", "Allure", "Chanel", Gender.WOMEN, "allure-women", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("049", "Dolce", "Dolce & Gabbana", Gender.WOMEN, "dolce", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("160M", "Burberry for Men", "Burberry", Gender.MEN, "burberry-for-men", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("051", "Coco Mademoiselle", "Chanel", Gender.WOMEN, "coco-mademoiselle", true, List.of(15, 30, 70), List.of("popular", "office")),
            new ProductSeed("052", "Pasha", "Cartier", Gender.MEN, "pasha", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("053", "Narciso", "Narciso Rodriguez", Gender.WOMEN, "narciso", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("054", "Black Orchid", "Tom Ford", Gender.UNISEX, "black-orchid", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("055", "Black Opium", "Yves Saint Laurent", Gender.WOMEN, "black-opium", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("056", "Ange ou Démon", "Givenchy", Gender.WOMEN, "ange-ou-demon", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("057", "Omnia Améthyste", "Bvlgari", Gender.WOMEN, "omnia-amethyste", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("061", "Invictus", "Paco Rabanne", Gender.MEN, "invictus", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("062", "Intenso", "Dolce & Gabbana", Gender.MEN, "intenso", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("064", "Omnia Indian Garnet", "Bvlgari", Gender.WOMEN, "omnia-indian-garnet", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("157M", "The Scent", "Hugo Boss", Gender.MEN, "the-scent", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("067", "Olympéa", "Paco Rabanne", Gender.WOMEN, "olympea", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("156W", "Hugo", "Hugo Boss", Gender.WOMEN, "hugo-women", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("068", "Aventus", "Creed", Gender.MEN, "aventus", true, List.of(15, 30, 70), List.of("popular", "signature")),
            new ProductSeed("069", "Acqua di Sale", "Profumum Roma", Gender.UNISEX, "acqua-di-sale", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("070", "The One", "Dolce & Gabbana", Gender.WOMEN, "the-one-women", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("071", "Allure", "Chanel", Gender.MEN, "allure-men", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("072", "Patchouli", "Reminiscence", Gender.UNISEX, "patchouli", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("073", "Himalaya", "Creed", Gender.MEN, "himalaya", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("074", "Black Afgano", "Nasomatto", Gender.UNISEX, "black-afgano", false, List.of(15, 50), List.of()),
            new ProductSeed("075", "X for Men", "Clive Christian", Gender.MEN, "x-for-men", false, List.of(15, 50), List.of()),
            new ProductSeed("076", "Acqua di Gioia", "Giorgio Armani", Gender.WOMEN, "acqua-di-gioia", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("158W", "Flora", "Gucci", Gender.WOMEN, "flora", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("079", "MYSLF", "Yves Saint Laurent", Gender.MEN, "myslf", true, List.of(15, 30, 70), List.of("popular", "office")),
            new ProductSeed("080", "Sì", "Giorgio Armani", Gender.WOMEN, "si", true, List.of(15, 30, 70), List.of("popular", "office")),
            new ProductSeed("081", "Classique Essence", "Jean Paul Gaultier", Gender.WOMEN, "classique-essence", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("082", "Signorina", "Salvatore Ferragamo", Gender.WOMEN, "signorina", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("083", "Uomo", "Roberto Cavalli", Gender.MEN, "uomo", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("084", "Dylan Blue", "Versace", Gender.MEN, "dylan-blue", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("085", "Chance", "Chanel", Gender.WOMEN, "chance", false, List.of(15, 30, 70), List.of("office")),
            new ProductSeed("086", "Legend", "Montblanc", Gender.MEN, "legend", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("087", "Wanted", "Azzaro", Gender.MEN, "wanted", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("088", "Man in Black", "Bvlgari", Gender.MEN, "man-in-black", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("089", "Mon Paris", "Yves Saint Laurent", Gender.WOMEN, "mon-paris", true, List.of(15, 30, 70), List.of("popular", "date-night")),
            new ProductSeed("090", "Poison Girl", "Christian Dior", Gender.WOMEN, "poison-girl", true, List.of(15, 30, 70), List.of("popular", "date-night")),
            new ProductSeed("091", "Chrome", "Azzaro", Gender.MEN, "chrome", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("092", "Mr. Burberry", "Burberry", Gender.MEN, "mr-burberry", false, List.of(15, 35, 100), List.of()),
            new ProductSeed("159W", "Burberry", "Burberry", Gender.WOMEN, "burberry-women", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("093", "Aventus for Her", "Creed", Gender.WOMEN, "aventus-for-her", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("094", "Sauvage", "Christian Dior", Gender.MEN, "sauvage", true, List.of(15, 30, 70), List.of("popular", "office")),
            new ProductSeed("096", "Gabrielle", "Chanel", Gender.WOMEN, "gabrielle", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("097", "Amo Ferragamo", "Salvatore Ferragamo", Gender.WOMEN, "amo-ferragamo", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("098", "Joy", "Christian Dior", Gender.WOMEN, "joy", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("099", "Mandarino di Amalfi", "Tom Ford", Gender.UNISEX, "mandarino-di-amalfi", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("100", "White Aoud", "Montale", Gender.UNISEX, "white-aoud", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("101", "Velvet Amber Skin", "Dolce & Gabbana", Gender.UNISEX, "velvet-amber-skin", false, List.of(15, 50), List.of()),
            new ProductSeed("102", "Velvet Amber Sun", "Dolce & Gabbana", Gender.UNISEX, "velvet-amber-sun", false, List.of(15, 50), List.of()),
            new ProductSeed("105", "Intense Café", "Montale", Gender.UNISEX, "intense-cafe", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("106", "Fucking Fabulous", "Tom Ford", Gender.UNISEX, "fucking-fabulous", false, List.of(15, 50), List.of()),
            new ProductSeed("109", "J’Adore l’Or", "Christian Dior", Gender.WOMEN, "jadore-lor", false, List.of(15, 50), List.of()),
            new ProductSeed("110", "Kirké", "Tiziana Terenzi", Gender.UNISEX, "kirke", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("111", "Lost Cherry", "Tom Ford", Gender.UNISEX, "lost-cherry", true, List.of(15, 50), List.of("date-night", "signature")),
            new ProductSeed("112", "Neroli Portofino", "Tom Ford", Gender.UNISEX, "neroli-portofino", false, List.of(15, 50), List.of("summer")),
            new ProductSeed("113", "Sur la Route", "Louis Vuitton", Gender.UNISEX, "sur-la-route", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("114", "Ombre Nomade", "Louis Vuitton", Gender.UNISEX, "ombre-nomade", true, List.of(15, 30, 70), List.of("signature", "winter")),
            new ProductSeed("115", "Idôle", "Lancôme", Gender.WOMEN, "idole", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("116", "Yes I Am", "Cacharel", Gender.WOMEN, "yes-i-am", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("117", "Tobacco Vanille", "Tom Ford", Gender.UNISEX, "tobacco-vanille", true, List.of(15, 50), List.of("winter", "date-night")),
            new ProductSeed("118", "Baccarat Rouge 540", "Maison Francis Kurkdjian", Gender.UNISEX, "baccarat-rouge-540", true, List.of(15, 50), List.of("signature", "date-night")),
            new ProductSeed("119", "Scandal", "Jean Paul Gaultier", Gender.WOMEN, "scandal", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("120", "La Petite Robe Noire", "Guerlain", Gender.WOMEN, "la-petite-robe-noire", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("121", "L’Interdit", "Givenchy", Gender.WOMEN, "linterdit", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("122", "Libre", "Yves Saint Laurent", Gender.WOMEN, "libre", true, List.of(15, 30, 70), List.of("popular", "signature")),
            new ProductSeed("123", "Good Girl Gone Bad", "Kilian", Gender.WOMEN, "good-girl-gone-bad", false, List.of(15, 50), List.of()),
            new ProductSeed("124", "Zeta", "Morph", Gender.UNISEX, "zeta", false, List.of(15, 50), List.of()),
            new ProductSeed("125", "Sole di Positano Acqua", "Tom Ford", Gender.UNISEX, "sole-di-positano-acqua", false, List.of(15, 50), List.of()),
            new ProductSeed("126", "Soleil Blanc", "Tom Ford", Gender.UNISEX, "soleil-blanc", false, List.of(15, 50), List.of()),
            new ProductSeed("127", "Oud Wood", "Tom Ford", Gender.UNISEX, "oud-wood", true, List.of(15, 50), List.of("office", "winter", "signature")),
            new ProductSeed("128", "Vanille Fatale", "Tom Ford", Gender.UNISEX, "vanille-fatale", false, List.of(15, 50), List.of()),
            new ProductSeed("129", "Erba Pura", "Xerjoff", Gender.UNISEX, "erba-pura", true, List.of(15, 50), List.of("summer", "signature")),
            new ProductSeed("130", "Megamare", "Orto Parisi", Gender.UNISEX, "megamare", false, List.of(15, 50), List.of()),
            new ProductSeed("131", "Good Girl", "Carolina Herrera", Gender.WOMEN, "good-girl", true, List.of(15, 30, 70), List.of("popular", "date-night")),
            new ProductSeed("132", "My Way", "Giorgio Armani", Gender.WOMEN, "my-way", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("133", "Prada Paradoxe", "Prada", Gender.WOMEN, "prada-paradoxe", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("134", "Bitter Peach", "Tom Ford", Gender.UNISEX, "bitter-peach", false, List.of(15, 50), List.of()),
            new ProductSeed("135", "Bois d’Argent", "Christian Dior", Gender.UNISEX, "bois-dargent", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("136", "Dior Homme Intense", "Christian Dior", Gender.MEN, "dior-homme-intense", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("137", "XJ 1861 Naxos", "Xerjoff", Gender.UNISEX, "xj-1861-naxos", false, List.of(15, 50), List.of()),
            new ProductSeed("138", "Whood Whisper", "Ojar", Gender.UNISEX, "whood-whisper", false, List.of(15, 50), List.of()),
            new ProductSeed("139", "Les Sables Roses", "Louis Vuitton", Gender.UNISEX, "les-sables-roses", false, List.of(15, 50), List.of()),
            new ProductSeed("140", "Éros", "Versace", Gender.MEN, "eros", true, List.of(15, 30, 70), List.of("popular", "date-night")),
            new ProductSeed("141", "Turath", "The Spirit of Dubai", Gender.UNISEX, "turath", false, List.of(15, 50), List.of()),
            new ProductSeed("142", "Ombré Leather", "Tom Ford", Gender.UNISEX, "ombre-leather", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("143", "Vanille Powder", "Matière Première", Gender.UNISEX, "vanille-powder", false, List.of(15, 50), List.of("winter", "date-night")),
            new ProductSeed("144", "Bianco Latte", "Giardini di Toscana", Gender.UNISEX, "bianco-latte", true, List.of(15, 50), List.of("winter", "date-night")),
            new ProductSeed("145", "Dévotion", "Dolce & Gabbana", Gender.WOMEN, "devotion", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("146", "Balmain Rouge", "Pierre Balmain", Gender.UNISEX, "balmain-rouge", false, List.of(15, 50), List.of("signature")),
            new ProductSeed("147M", "Bottled Absolu", "Hugo Boss", Gender.MEN, "bottled-absolu", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("148W", "Goddess", "Burberry", Gender.WOMEN, "goddess", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("161W", "Valentino Donna Born In Roma Intense", "Valentino", Gender.WOMEN, "valentino-donna-born-in-roma-intense", false, List.of(15, 30, 70), List.of()),
            new ProductSeed("162M", "Valentino Uomo Born In Roma Intense", "Valentino", Gender.MEN, "valentino-uomo-born-in-roma-intense", true, List.of(15, 30, 70), List.of("popular", "date-night"))
        );
    }

    record ProductSeed(
            String perfumeNumber,
            String name,
            String brand,
            Gender gender,
            String slug,
            boolean featured,
            List<Integer> sizes,
            List<String> categorySlugs
    ) {}
}
